version: '3.1'
services:
    couchdb:
        image: couchdb
        container_name: verv-couchdb
        ports:
            - 5984:5984
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: password

#COUCH1=$(docker run -d -p 5984 -v /var/lib/couchdb couchdb)
# $ HOST=localhost
# $ URL="http://$HOST:$(docker port $COUCH1 5984 | grep -o '[1-9][0-9]*$')/_utils/"
# $ echo "Navigate to $URL in your browser, and use the couch interface to add data"
